#!/usr/bin/env python
# jenkode v0.2 (2021-06-17) (ba491a568f607f6e)
#  ▐▄▄▄▄▄▄ ..▄▄ · ▄• ▄▌.▄▄ · 
#  ·██▀▄.▀·▐█ ▀. █▪██▌▐█ ▀.  you don't want to be here
#▪▄ ██▐▀▀▪▄▄▀▀▀█▄█▌▐█▌▄▀▀▀█▄ I don't want to be here
#▐▌▐█▌▐█▄▄▌▐█▄▪▐█▐█▄█▌▐█▄▪▐█ but we are both here
# ▀▀▀• ▀▀▀  ▀▀▀▀  ▀▀▀  ▀▀▀▀ 
#
#          ▄▄ •  ▄▄▄·  ▌ ▐·▄▄▄ .    ▄• ▄▌ ▄▄▄·
#        ▐█ ▀ ▪▐█ ▀█ ▪█·█▌▀▄.▀·    █▪██▌▐█ ▄█
# I just ▄█ ▀█▄▄█▀▀█ ▐█▐█•▐▀▀▪▄    █▌▐█▌ ██▀·
#        ▐█▄▪▐█▐█ ▪▐▌ ███ ▐█▄▄▌    ▐█▄█▌▐█▪·•
#        ·▀▀▀▀  ▀  ▀ . ▀   ▀▀▀      ▀▀▀ .▀   
#                       and did this
import sys
def usage():
    sys.stderr.write("fam pass me something in stdin and then either -e/--encode or -d/--decode as 1st param and then pass me the groovy version you want to target as 2nd param - because haha yeah there is no stable string-literal version to target because they changed what they escape between versions, haha yes really, they did, like you might ask why, I am with you, the thing is, I don't _actually_ wanna know, I just don't want to set a default and then it blows up for you again during usage and you have to figure out why, you can look the groovy-version up on a running jenkins instance if you go to 'Manage Jenkins' => 'About Jenkins', and then you can see like org.codehaus.groovy:groovy-all:X.Y.Z and then you pass me 'X.Y.Z', take care fam\n")
    sys.exit(1)
if len(sys.argv) != 3: usage()
# see https://groovy-lang.org/syntax.html#_escaping_special_characters
version=[ int(d) for d in sys.argv[2].split(".") ]
if version < [3,0,3]:
    escapem=['t'   , 'b'   , 'n'   , 'r'   , 'f'   , '\\'   , '\''   , '"']
    escapee=['\t'  , '\b'  , '\n'  , '\r'  , '\f'  , '\\'   , '\''   , '"']
    escaped=['\\t' , '\\b' , '\\n' , '\\r' , '\\f' , '\\\\' , '\\\'' , '\\"']
else:
    escapem=['b'   , 'f'   , 'n'   , 'r'   , 's'  , 't'   , '\\'   , '\''   , '"']
    escapee=['\b'  , '\f'  , '\n'  , '\r'  , ' '  , '\t'  , '\\'   , '\''   , '"']
    escaped=['\\b' , '\\f' , '\\n' , '\\r' , '\s' , '\\t' , '\\\\' , '\\\'' , '\\"']
if sys.argv[1] in ["-e","--encode"]:
    result="'"
    for line in sys.stdin:
        for c in line:
            if c == '\0':
                break
            elif c in escapee:
                result+=escaped[escapee.index(c)]
            else:
                result+=c
    result+="'"
    sys.stdout.write(result)
    sys.stdout.write("\n")
    sys.stdout.flush()
elif sys.argv[1] in ["-d","--decode"]:
    result=""
    first=True
    for line in sys.stdin:
        if first:
            line=line[1:]
            first=False
        line=line+'\0'
        i=0
        while True:
            c=line[i]
            if c == '\0':
                break
            elif c == '\\':
                i+=1
                c=line[i]
                if c == '\0':
                    break
                elif c in escapem:
                    result+=escapee[escapem.index(c)]
                elif c == "0":
                    raise Exception("Smelly socks")
                else:
                    result+=c
            else:
                result+=c
            i+=1
    sys.stdout.write(result[:-2])
    sys.stdout.flush()
else:
    usage()
